---
- name: Get resource group
  ibm.cloudcollection.ibm_resource_group_info:
    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    name: "{{ satellite_location_resource_group }}"
  register: satellite_resource_group
  run_once: true
  delegate_to: localhost

- name: Create Satellite location
  ibm.cloudcollection.ibm_satellite_location:
    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    location: "{{ satellite_location_name }}"
    managed_from: "{{ satellite_location_manage_from }}"
    resource_group_id: "{{ satellite_resource_group.resource.id }}"
    description: Created-with-ansible
    region: "{{ satellite_location_region }}"
    tags: ansible
  when: "hostvars['dummy']['deployed_hosts'] is not defined"
  register: satellite_location
  run_once: true
  delegate_to: localhost
