satellite_virtual_machines:
  - name: cn01
    id: controlplane1
    disk_size: 100
    disk_type: thin
    host_prefix: controlplane
    ip: 192.168.2.100
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: controlplane
  - name: cn02
    id: controlplane2
    disk_size: 100
    disk_type: thin
    host_prefix: controlplane
    ip: 192.168.2.101
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: controlplane
  - name: cn03
    id: controlplane3
    disk_size: 100
    disk_type: thin
    host_prefix: controlplane
    ip: 192.168.2.102
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: controlplane
  - name: wk01
    id: worker1
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.103
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker
  - name: wk02
    id: worker2
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.104
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker
  - name: wk03
    id: worker3
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.105
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker
  - name: wk04
    id: worker4
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.106
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker
  - name: wk05
    id: worker5
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.107
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker
  - name: wk06
    id: worker6
    disk_size: 100
    disk_type: thin
    host_prefix: worker
    ip: 192.168.2.108
    netmask: 255.255.255.0
    gateway: 192.168.2.1
    memory: 16384
    vcpu: 4
    notes: worker

create_jumphost: true
jumphost:
  ip: "10.45.131.80"
  user: "root"

host_user: "root"
host_password: "{{ vault_root_password }}"
external_url: "www.google.com"

sat_host_dns_server: 8.8.8.8
sat_host_domain_name: ""
ibmcloud_api_key: "{{ vault_ibmcloud_api_key }}"
# NEED TO BE MODIFIED
satellite_location_name: ansible-location
# ibmcloud ks locations
satellite_location_manage_from: lon
# ibmcloud resource groups
satellite_location_resource_group: satellite
satellite_location_region: eu-gb
sat_host_prefix: "satellite"

#Redhat details needed for registration

redhat_username: "{{ vault_redhat_user }}"
redhat_password: "{{ vault_redhat_password }}"
#organization: "{{ vault_organization }}"
#activation_key: "{{ vault_activation_key }}"

#VmWare connection details

vcenter_hostname: "vcszm-vc.psm.sandbox.local"
vcenter_username: "{{ vault_vcenter_username }}"
vcenter_password: "{{ vault_vcenter_password }}"

vmware_datacenter: "IBMCloud"
vmware_datastore: "workload_share_Jc5ar"
vmware_cluster: "vcs-zm-consolidated"
vmware_network: "T0-192-168-2-0"
vmware_template: "RHEL79-TEMPLATE"
vmware_folder: "SATELLITE"
